name: Quality Control

on: push

jobs:
  quality-control:
    name: Perform code quality checks
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Checkout
        uses: actions/checkout@v4
      - name: Installation
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Linting
        run: flake8
      - name: Typing
        run: mypy
      - name: Testing
        run: python -m unittest

